/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/v1/endpoints/{endpoint_slug}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Submit your data to an endpoint
     * @description Submit your data bb
     */
    post: operations['submit']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    SubmissionInput: {
      /**
       * @example {
       *       "name": "Test Testerson",
       *       "email": "test@testerson.com",
       *       "message": "Greetings"
       *     }
       */
      data: {
        [key: string]: unknown
      }
      options?: {
        /**
         * @example raw
         * @enum {string}
         */
        submission_format?: 'raw' | 'pretty'
        /**
         * @example ping
         * @enum {string}
         */
        submission_sound?: 'none' | 'ping'
        /** @example false */
        email_notification?: boolean
      }
    }
    Submission: {
      /** Format: date-time */
      created_at?: string
      /**
       * @example {
       *       "name": "Test Testerson",
       *       "email": "test@testerson.com",
       *       "message": "Greetings"
       *     }
       */
      data?: Record<string, never>
      /** @example false */
      email_notification?: boolean
      email_status?: null | string
      /** @example 12345 */
      endpoint_id?: number
      /** @example Test Contact Form */
      endpoint_name?: string
      /** @example XxJqpisK8 */
      endpoint_slug?: string
      /** Format: date-time */
      seen_at?: string | null
      /** @enum {string} */
      submission_format?: 'raw' | 'pretty'
      /** @example xxxx-xxxx-xxxx-xxx */
      submission_id?: string
      /**
       * @example ping
       * @enum {string}
       */
      submission_sound?: 'none' | 'ping'
      /** @example 12345 */
      user_id?: number
    }
    ErrorResponse: {
      /** @example 🙈 */
      message?: string
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  submit: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description the slug of the endpoint */
        endpoint_slug: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['SubmissionInput']
      }
    }
    responses: {
      /** @description Returns the new submission */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Submission']
        }
      }
      /** @description Endpoint is disabled */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Submission limit reached */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Endpoint not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Invalid request body */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
}
