/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/v1/endpoints': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get all user endpoints
     * @description Retrieve all endpoints for the authenticated user with optional sorting
     */
    get: operations['findUserEndpoints']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/v1/endpoints/{slug}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get a single endpoint by slug
     * @description Retrieve a single endpoint with associated integrations and origins
     */
    get: operations['findEndpoint']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/v1/endpoints/{slug}/submissions': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get all submissions for an endpoint
     * @description Retrieve paginated submissions for an endpoint with filtering options
     */
    get: operations['findEndpointSubmissions']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/v1/projects': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get all user projects
     * @description Retrieve all projects for the authenticated user with optional sorting
     */
    get: operations['findUserProjects']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/v1/projects/{slug}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get a single project by slug
     * @description Retrieve a single project with associated endpoints, integrations, and origins
     */
    get: operations['findProject']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/v1/projects/{slug}/endpoints': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get all endpoints for a project
     * @description Retrieve all endpoints associated with a project
     */
    get: operations['findProjectEndpoints']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/v1/projects/{slug}/submissions': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get all submissions for a project
     * @description Retrieve paginated submissions for a project with filtering options
     */
    get: operations['findProjectSubmissions']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/v1/submissions': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get user submissions with pagination and filtering
     * @description Retrieve paginated list of submissions for authenticated user
     */
    get: operations['findUserSubmissions']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/v1/submissions/{id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get a single submission by ID
     * @description Retrieve a single submission with webhook events
     */
    get: operations['findSubmission']
    put?: never
    post?: never
    /**
     * Delete a submission
     * @description Delete a submission and decrement endpoint submission count
     */
    delete: operations['deleteSubmission']
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/v1/submit/{slug}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Submit your data to an endpoint
     * @description Submit JSON and get notified in real-time
     */
    post: operations['submit']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    ActivityLog: {
      /**
       * Format: uuid
       * @example xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
       */
      logId?: string
      /**
       * Format: uuid
       * @example xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
       */
      userId?: string
      /**
       * Format: uuid
       * @example xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
       */
      submissionId?: string
      /**
       * Format: uuid
       * @example xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
       */
      endpointId?: string
      /** @example discord_sent */
      eventType?: string
      /**
       * @example discord
       * @enum {string}
       */
      eventCategory?: 'submission' | 'email' | 'webhook' | 'telegram' | 'slack' | 'discord' | 'google_sheets' | 'zapier' | 'integration'
      /**
       * @example success
       * @enum {string}
       */
      status?: 'pending' | 'success' | 'error' | 'warning' | 'info'
      /** @example Discord notification sent successfully */
      message?: string
      /**
       * @example {
       *       "channel": "#notifications",
       *       "messageId": "1234567890"
       *     }
       */
      metadata?: {
        [key: string]: unknown
      }
      /** @example null */
      errorDetails?: string
      /** Format: date-time */
      createdAt?: string
    }
    DiscordWebhook: {
      /** @example xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx */
      discordWebhookId?: string
      /** @example 1234567890123456789 */
      discordChannelId?: string
      /** @example #notifications */
      discordChannelName?: string
      /** @example My Discord Server */
      discordGuildName?: string
    }
    Endpoint: {
      /**
       * Format: uuid
       * @example xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
       */
      endpointId?: string
      /**
       * Format: uuid
       * @example xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
       */
      projectId?: string
      /**
       * Format: uuid
       * @example xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
       */
      userId?: string
      /** @example XxXxXxX */
      endpointSlug?: string
      /** @example Contact Form */
      endpointName?: string
      /**
       * @example enabled
       * @enum {string}
       */
      endpointStatus?: 'enabled' | 'disabled'
      /** @example Main contact form for website */
      endpointDescription?: string
      /** @example 150 */
      submissionCount?: number
      /** @example 145 */
      emailCount?: number
      /**
       * @example pretty
       * @enum {string}
       */
      endpointFormat?: 'raw' | 'pretty' | 'custom'
      /**
       * @description Supports plain placeholders and safe HTML tags: b, strong, i, em, u, ul, ol, li, p, br.
       * @example <p><strong>New lead</strong></p><p>Name: {{name}}</p><ul><li>Email: {{email}}</li></ul>
       */
      endpointTemplate?: string | null
      /**
       * Format: uri
       * @example https://acme.com/thank-you
       */
      endpointFrontendUrl?: string | null
      /** @example true */
      emailNotificationsEnabled?: boolean
      /**
       * Format: email
       * @example contact@example.com
       */
      endpointTo?: string
      /** @example team@example.com,alerts@example.com */
      endpointCc?: string | null
      /**
       * @example ping
       * @enum {string}
       */
      endpointSound?: 'none' | 'beep' | 'blip' | 'block' | 'coin' | 'ding' | 'dink' | 'honk' | 'jump' | 'ping' | 'pong' | 'snare'
      /** @example New submission from {endpoint} */
      endpointSubject?: string | null
      /** @example Your Business Name */
      endpointFromName?: string | null
      /**
       * Format: uuid
       * @example xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
       */
      endpointSmtpServerId?: string | null
      /**
       * @example system
       * @enum {string}
       */
      endpointEmailDeliveryMode?: 'system' | 'smtp'
      /** @description Endpoint-level email auto-responder configuration. */
      endpointAutoResponder?: (components['schemas']['AutoResponderConfig'] | null) & components['schemas']['AutoResponderConfig']
      /** @example true */
      endpointBranding?: boolean
      /** @example 5 */
      blockedSubmissionCount?: number
      /** @example false */
      secretKeyRequired?: boolean
      /** @example website */
      endpointHoneypot?: string | null
      /**
       * @example turnstile
       * @enum {string}
       */
      endpointCaptcha?: 'none' | 'recaptcha' | 'turnstile' | 'hcaptcha'
      /** @example xxxxxxxxxxxxx */
      recaptchaSecret?: string | null
      /** @example xxxxxxxxxxxxx */
      turnstileSecret?: string | null
      /** @example xxxxxxxxxxxxx */
      hcaptchaSecret?: string | null
      /** Format: date-time */
      lastSubmission?: string
      /** @example false */
      discordNotificationsEnabled?: boolean
      /** @example xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx */
      discordWebhookId?: string
      /** @example #notifications - Your Server */
      discordChannel?: string
      /** @example 1BxiMVs0XRA5nFMdKvBdBZjgmUUqptlbs74OgvE2upms */
      googleSheetsId?: string
      /**
       * Format: uri
       * @example https://docs.google.com/spreadsheets/d/xxx
       */
      googleSheetsUrl?: string
      /** @example false */
      googleSheetsEnabled?: boolean
      /**
       * Format: email
       * @example service@example.iam.gserviceaccount.com
       */
      googleSheetsAccountEmail?: string
      /** @example false */
      slackNotificationsEnabled?: boolean
      /** @example #general */
      slackChannel?: string | null
      /** @example xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx */
      slackWorkspaceId?: string
      /** @example -1001234567890 */
      telegramChatId?: string | null
      /** @example My Telegram Channel */
      telegramName?: string | null
      /** @example false */
      telegramNotificationsEnabled?: boolean
      /** Format: date-time */
      createdAt?: string
      /**
       * Format: uri
       * @example https://hooks.zapier.com/hooks/catch/xxx
       */
      zapierHookUrl?: string
      /** @example 123456 */
      zapierZapId?: string
      /** @example 50 */
      endpointPeriodSubmissionCount?: number
      /** @example 2 */
      endpointPeriodBlockedSubmissionCount?: number
      /** @example 48 */
      endpointPeriodEmailCount?: number
      /** @example 1000 */
      submissionLimit?: number | null
      /** @example email */
      uniqueKey?: string | null
      /** Format: date-time */
      disableAt?: string | null
    }
    Origin: {
      /**
       * Format: uuid
       * @example xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
       */
      originId?: string
      /**
       * Format: uri
       * @example https://example.com
       */
      originUrl?: string
      /**
       * Format: uuid
       * @example xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
       */
      endpointId?: string | null
      /**
       * Format: uuid
       * @example xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
       */
      projectId?: string | null
      /**
       * Format: uuid
       * @example xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
       */
      userId?: string
      /** Format: date-time */
      createdAt?: string
    }
    Project: {
      /**
       * Format: uuid
       * @example xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
       */
      projectId?: string
      /** @example My Website Forms */
      projectName?: string
      /** @example XxXxXxX */
      projectSlug?: string
      /** @example 5 */
      projectEndpointCount?: number
      /** @example 1250 */
      projectSubmissionCount?: number
      /** @example 42 */
      projectBlockedSubmissionCount?: number
      /**
       * @example enabled
       * @enum {string}
       */
      projectStatus?: 'enabled' | 'disabled'
      /** Format: date-time */
      projectLastSubmission?: string | null
      /** @example true */
      projectEmailNotificationsEnabled?: boolean
      /**
       * Format: email
       * @example yo@yoerson.com
       */
      projectTo?: string
      /** @example team@example.com,alerts@example.com */
      projectCc?: string | null
      /**
       * @example pretty
       * @enum {string}
       */
      projectFormat?: 'raw' | 'pretty' | 'custom'
      /**
       * @description Supports plain placeholders and safe HTML tags: b, strong, i, em, u, ul, ol, li, p, br.
       * @example <p><em>Submission from {{data.name}}</em></p><ol><li>{{data.email}}</li></ol>
       */
      projectTemplate?: string | null
      /**
       * @example ping
       * @enum {string}
       */
      projectSound?: 'none' | 'beep' | 'blip' | 'block' | 'coin' | 'ding' | 'dink' | 'honk' | 'jump' | 'ping' | 'pong' | 'snare'
      /** @example New submission from {endpoint} */
      projectSubject?: string | null
      /** @example Your Business Name */
      projectFromName?: string | null
      /**
       * Format: uuid
       * @example xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
       */
      projectSmtpServerId?: string | null
      /**
       * @example system
       * @enum {string}
       */
      projectEmailDeliveryMode?: 'system' | 'smtp'
      /** @description Project-level default email auto-responder configuration. */
      projectAutoResponder?: (components['schemas']['AutoResponderConfig'] | null) & components['schemas']['AutoResponderConfig']
      /** @example true */
      projectBranding?: boolean
      /** @example website */
      projectHoneypot?: string
      /**
       * @example turnstile
       * @enum {string}
       */
      projectCaptcha?: 'none' | 'recaptcha' | 'turnstile' | 'hcaptcha'
      /** @example xxxxxxxxxxxxx */
      projectRecaptchaSecret?: string | null
      /** @example xxxxxxxxxxxxx */
      projectTurnstileSecret?: string | null
      /** @example xxxxxxxxxxxxx */
      projectHcaptchaSecret?: string | null
      /** @example false */
      projectDiscordNotificationsEnabled?: boolean
      /** @example xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx */
      projectDiscordWebhookId?: string
      /** @example #notifications - Your Server */
      projectDiscordChannel?: string
      /** @example false */
      projectSlackNotificationsEnabled?: boolean
      /** @example #notifications */
      projectSlackChannel?: string | null
      /** @example 150 */
      projectPeriodSubmissionCount?: number
      /** @example 5 */
      projectPeriodBlockedSubmissionCount?: number
      /** @example 145 */
      projectPeriodEmailCount?: number
      /** Format: date-time */
      projectDisableAt?: string | null
      /** @example 1000 */
      projectSubmissionLimit?: number | null
      /** @example email */
      projectUniqueKey?: string | null
      /** @example false */
      projectSecretKeyRequired?: boolean
      /** @example xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx */
      slackWorkspaceId?: string
      /**
       * Format: uuid
       * @example xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
       */
      userId?: string
      /** Format: date-time */
      createdAt?: string
    }
    SlackWorkspace: {
      /** @example xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx */
      slackWorkspaceId?: string
      /** @example My Company Workspace */
      slackWorkspaceName?: string
      channels?: {
        /** @example C1234567890 */
        channelId?: string
        /** @example #general */
        channelName?: string
      }[]
    }
    AutoResponderConfig: {
      /** @example true */
      enabled?: boolean
      /**
       * @description Dot-path into submission data used as recipient.
       * @example email
       */
      toField?: string
      /** @example Thanks for contacting us, {{name}} */
      subject?: string
      /** @example Hi {{name}}, we received your message and will reply soon. */
      template?: string
      /** @example Acme Support */
      fromName?: string | null
      /**
       * Format: email
       * @example support@acme.com
       */
      replyTo?: string
    }
    SubmissionEmailAutoResponder: {
      /** @enum {string} */
      status?: 'disabled' | 'pending' | 'sent' | 'send-failed' | 'skipped-missing-field' | 'skipped-invalid-email' | 'skipped-smtp-unavailable'
      /** @example email */
      toField?: string
      /** @example Thanks for contacting us, {{name}} */
      subject?: string
      /** @example Hi {{name}}, we received your message and will reply soon. */
      template?: string
      /** @example Acme Support */
      fromName?: string | null
      /**
       * Format: email
       * @example support@acme.com
       */
      replyTo?: string
      /**
       * Format: email
       * @example customer@example.com
       */
      to?: string
      /** Format: date-time */
      sentAt?: string
      error?: string
    }
    SubmissionInput: {
      /**
       * @description The data to submit, must be a valid JSON object
       * @example {
       *       "name": "Yo Yoerson",
       *       "email": "yo@yoerson.com",
       *       "message": "Yo",
       *       "powerLevel": 9001
       *     }
       */
      data: {
        [key: string]: unknown
      }
      /** @description Configure submission options, overriding the endpoint's settings. */
      options?: {
        /**
         * @description Send an email notification
         * @example false
         */
        emailNotification?: boolean
        /**
         * @description The "To" recipient of the email notification
         * @example yo@yoerson.com
         */
        emailTo?: string
        /**
         * @description Optional comma-separated CC recipients. Each address must be a verified linked email on your account.
         * @example team@example.com,ops@example.com
         */
        emailCc?: string
        /**
         * @description Set a ReplyTo for the email notification
         * @example yo@yoerson.com
         */
        emailReplyTo?: string
        /**
         * @description Change the default email notification subject. Available on Pro & Scale plans.
         * @example My custom email subject
         */
        emailSubject?: string
        /**
         * @description Change the default email notification from name. Available on Pro & Scale plans.
         * @example Your Business
         */
        emailFromName?: string
        /**
         * @description Remove Submit JSON branding from the email notification. Available on Pro & Scale plans.
         * @example true
         */
        emailBranding?: boolean
        /** @description Override endpoint auto-responder content for this submission. Available when using SMTP. */
        emailAutoResponder?: {
          /**
           * @description Override auto-responder subject for this submission.
           * @example Thanks for reaching out, {{name}}
           */
          subject?: string
          /**
           * @description Override auto-responder template for this submission. Supports safe HTML tags and {{variables}}.
           * @example <p>Hi {{name}},</p><p>Thanks for contacting us.</p>
           */
          template?: string
        }
        /**
         * @description Set the format of the submission to raw JSON, pretty, or custom
         * @example raw
         * @enum {string}
         */
        submissionFormat?: 'raw' | 'pretty' | 'custom'
        /**
         * @description Supports {{path.to.value}} placeholders, {{#if}}/{{else if}}/{{else}}/{{/if}}, {{#unless}} blocks, and safe HTML tags (b, strong, i, em, u, ul, ol, li, p, br, a). If provided, it takes precedence over endpoint defaults.
         * @example <p><strong>Lead</strong>: {{name}}</p><p>Email: {{email}}</p><ul><li>{{data.message}}</li></ul>
         */
        submissionTemplate?: string
        /**
         * @description Play a sound on submitjson.com upon submission
         * @example ping
         * @enum {string}
         */
        submissionSound?: 'none' | 'beep' | 'blip' | 'block' | 'coin' | 'ding' | 'dink' | 'honk' | 'jump' | 'ping' | 'pong' | 'snare'
        /**
         * @description Pass a reCAPTCHA response token along with the submission. Available on all paid plans.
         * @example xxxxxxxxxxxxx
         */
        recaptchaToken?: string
        /**
         * @description Pass a Cloudflare Turnstile response token along with the submission. Available on all paid plans.
         * @example xxxxxxxxxxxxx
         */
        turnstileToken?: string
        /**
         * @description Pass a hCaptcha response token along with the submission. Available on all paid plans.
         * @example xxxxxxxxxxxxx
         */
        hcaptchaToken?: string
        /**
         * @description Send a Discord notification. Endpoint must be integrated with Discord. Available on Pro & Scale plans.
         * @example false
         */
        discordNotification?: boolean
        /**
         * @description Send a Slack notification. Endpoint must be integrated with Slack. Available on Pro & Scale plans.
         * @example false
         */
        slackNotification?: boolean
        /**
         * @description Send a Telegram notification. Endpoint must be connected to Telegram. Available on Pro & Scale plans.
         * @example false
         */
        telegramNotification?: boolean
      }
    }
    Submission: {
      /** Format: date-time */
      createdAt?: string
      /**
       * @example {
       *       "name": "Yo Yoerson",
       *       "email": "yo@yoerson.com",
       *       "message": "Yo",
       *       "powerLevel": 9001
       *     }
       */
      data?: Record<string, never>
      /** @example #notifications - Your Server */
      discordChannel?: string | null
      /** @enum {string|null} */
      discordStatus?: 'pending' | 'success' | 'error' | 'error-char-limit' | null
      /** @example true */
      emailBranding?: boolean
      /** @example false */
      emailNotification?: boolean
      /** @example yo@yoerson.com */
      emailTo?: string | null
      /** @example team@example.com,ops@example.com */
      emailCc?: string | null
      /** @example yo@yoerson.com */
      emailReplyTo?: string | null
      /** @enum {string|null} */
      emailStatus?: 'pending' | 'delivered' | 'sent' | 'opened' | 'bounced' | 'limit-reached' | 'invalid-recipient' | 'spam-complaint' | 'delivery-delayed' | 'send-failed' | 'error' | null
      /** @example Endpoint name {xxxyyzz} */
      emailSubject?: string
      /**
       * @description Actual email delivery path used for this submission. Null when no email send was attempted.
       * @example smtp
       * @enum {string|null}
       */
      emailDeliveryMode?: 'system' | 'smtp' | null
      /** @description Snapshot and execution status for the email auto-responder. Null when auto-responder is disabled. */
      emailAutoResponder?: (components['schemas']['SubmissionEmailAutoResponder'] | null) & components['schemas']['SubmissionEmailAutoResponder']
      /** @example Your client's business */
      emailFromName?: string
      /** @example xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx */
      endpointId?: string
      /** @example Test Contact Form */
      endpointName?: string
      /** @example XxJqpisK8 */
      endpointSlug?: string
      /** @enum {string|null} */
      googleSheetsStatus?: 'pending' | 'success' | 'error' | null
      /** @example https://docs.google.com/spreadsheets/d/{id}/edit */
      googleSheetsUrl?: string | null
      /** Format: date-time */
      seenAt?: string | null
      /**
       * @example true
       * @enum {string|null}
       */
      securityCaptcha?: 'hcaptcha' | 'recaptcha' | 'turnstile' | null
      /** @example true */
      securityCors?: boolean
      /** @example false */
      securityHoneypot?: boolean
      /** @example null */
      slackChannel?: string
      /** @enum {string|null} */
      slackStatus?: 'pending' | 'success' | 'error' | null
      /** @enum {string} */
      submissionFormat?: 'raw' | 'pretty' | 'custom'
      /** @example <p><strong>Lead</strong>: {{name}}</p><p>Email: {{email}}</p> */
      submissionTemplate?: string | null
      /** @example <p><strong>Lead</strong>: Alice</p><p>Email: alice@example.com</p> */
      submissionTemplateRendered?: string | null
      /** @example xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx */
      submissionId?: string
      /**
       * Format: uri
       * @example https://www.yourwebsite.com
       */
      submissionOrigin?: string | null
      /** @example ping */
      submissionSound?: string
      /** @example Your Name - @username */
      telegramName?: string | null
      /** @enum {string|null} */
      telegramStatus?: 'pending' | 'success' | 'error' | 'error-char-limit' | null
      /** @example email */
      uniqueKey?: string
      /** @example xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx */
      userId?: string
      /** @enum {string|null} */
      webhookStatus?: 'success' | 'partial-success' | 'error' | null
      /** @enum {string|null} */
      zapierStatus?: 'pending' | 'success' | 'error' | null
    }
    SubmissionWithLogs: components['schemas']['Submission'] & {
      webhookEvents?: components['schemas']['WebhookEvent'][]
      logs?: components['schemas']['ActivityLog'][]
    }
    Webhook: {
      /**
       * Format: uuid
       * @example xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
       */
      webhookId?: string
      /**
       * Format: uuid
       * @example xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
       */
      userId?: string
      /**
       * Format: uuid
       * @example xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
       */
      endpointId?: string
      /**
       * Format: uri
       * @example https://api.example.com/webhook
       */
      webhookUrl?: string
      webhookHeaders?: {
        /** @example Authorization */
        key?: string
        /** @example Bearer token123 */
        value?: string
      }[]
      /** Format: date-time */
      lastUsed?: string
      /** Format: date-time */
      createdAt?: string
    }
    WebhookEvent: {
      /**
       * Format: uuid
       * @example xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
       */
      webhookEventId?: string
      /**
       * Format: uuid
       * @example xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
       */
      webhookId?: string
      /**
       * Format: uuid
       * @example xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
       */
      userId?: string
      /**
       * Format: uuid
       * @example xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
       */
      endpointId?: string
      /**
       * Format: uuid
       * @example xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
       */
      submissionId?: string
      /** @example 200 */
      responseStatus?: number
      /**
       * Format: uri
       * @example https://api.example.com/webhook
       */
      requestUrl?: string
      /** Format: date-time */
      createdAt?: string
    }
    ErrorResponse: {
      /** @example 🙈 */
      message?: string
      /** @example 400 */
      statusCode?: unknown
    }
  }
  responses: never
  parameters: {
    /** @description Page number for pagination */
    PageParam: number
    /** @description Number of items per page */
    LimitParam: number
    /** @description Sort order */
    OrderParam: 'asc' | 'desc'
    /** @description Filter by time period */
    PeriodParam: 'day' | 'week' | 'month' | '3months' | '6months' | 'year' | 'all'
    /** @description Search submissions by UUID or text content */
    SearchParam: string
    /** @description Filter by read status */
    StatusParam: 'all' | 'new' | 'seen'
    /** @description Filter by project slug */
    ProjectParam: string
  }
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  findUserEndpoints: {
    parameters: {
      query?: {
        /** @description Sort endpoints by criteria */
        sort?: 'name' | 'new' | 'old' | 'submissions' | 'activity'
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Returns array of endpoints */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Endpoint'][]
        }
      }
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  findEndpoint: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Endpoint slug */
        slug: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Returns the endpoint with related data */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            endpoint?: components['schemas']['Endpoint']
            webhooks?: components['schemas']['Webhook'][]
            slackWorkspaces?: components['schemas']['SlackWorkspace'][]
            discordWebhooks?: components['schemas']['DiscordWebhook'][]
            origins?: components['schemas']['Origin'][]
          }
        }
      }
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Endpoint not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  findEndpointSubmissions: {
    parameters: {
      query?: {
        /** @description Page number for pagination */
        page?: components['parameters']['PageParam']
        /** @description Sort order */
        order?: components['parameters']['OrderParam']
        /** @description Filter by time period */
        period?: components['parameters']['PeriodParam']
        /** @description Search submissions by UUID or text content */
        search?: components['parameters']['SearchParam']
        /** @description Filter by read status */
        status?: components['parameters']['StatusParam']
      }
      header?: never
      path: {
        /** @description Endpoint slug */
        slug: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Returns paginated submissions */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            submissions?: components['schemas']['Submission'][]
            submissionCount?: number
            totalPages?: number
            currentPage?: number
          }
        }
      }
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Endpoint not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Invalid query parameters */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  findUserProjects: {
    parameters: {
      query?: {
        /** @description Sort projects by criteria */
        sort?: 'name' | 'new' | 'old' | 'submissions' | 'activity'
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Returns array of projects */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Project'][]
        }
      }
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  findProject: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Project slug */
        slug: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Returns the project with related data */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            project?: components['schemas']['Project']
            endpoints?: components['schemas']['Endpoint'][]
            slackWorkspaces?: components['schemas']['SlackWorkspace'][]
            discordWebhooks?: components['schemas']['DiscordWebhook'][]
            origins?: components['schemas']['Origin'][]
          }
        }
      }
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Project not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  findProjectEndpoints: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Project slug */
        slug: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Returns array of endpoints */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Endpoint'][]
        }
      }
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Project not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  findProjectSubmissions: {
    parameters: {
      query?: {
        /** @description Page number for pagination */
        page?: components['parameters']['PageParam']
        /** @description Sort order */
        order?: components['parameters']['OrderParam']
        /** @description Filter by time period */
        period?: components['parameters']['PeriodParam']
        /** @description Search submissions by UUID or text content */
        search?: components['parameters']['SearchParam']
        /** @description Filter by read status */
        status?: components['parameters']['StatusParam']
      }
      header?: never
      path: {
        /** @description Project slug */
        slug: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Returns paginated submissions */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            submissions?: components['schemas']['Submission'][]
            submissionCount?: number
            totalPages?: number
            currentPage?: number
          }
        }
      }
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Project not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Invalid query parameters */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  findUserSubmissions: {
    parameters: {
      query?: {
        /** @description Page number for pagination */
        page?: components['parameters']['PageParam']
        /** @description Sort order */
        order?: components['parameters']['OrderParam']
        /** @description Filter by time period */
        period?: components['parameters']['PeriodParam']
        /** @description Search submissions by UUID or text content */
        search?: components['parameters']['SearchParam']
        /** @description Filter by read status */
        status?: components['parameters']['StatusParam']
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Returns paginated submissions */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            submissions?: components['schemas']['Submission'][]
            submissionCount?: number
            totalPages?: number
            currentPage?: number
          }
        }
      }
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Invalid query parameters */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  findSubmission: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Submission ID */
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Returns the submission */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['SubmissionWithLogs']
        }
      }
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Submission not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  deleteSubmission: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Submission ID */
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Submission deleted successfully */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Submission not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  submit: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description The slug of the Endpoint */
        slug: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['SubmissionInput']
      }
    }
    responses: {
      /** @description Returns the new submission */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Submission']
        }
      }
      /** @description Endpoint is disabled */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Submission limit reached */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Endpoint not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Invalid request body */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
}
